// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// kalmanUpdate
Eigen::MatrixXd kalmanUpdate(Eigen::MatrixXd Y, Eigen::MatrixXd X, Eigen::MatrixXd F, Eigen::MatrixXd H, Eigen::MatrixXd Q, Eigen::MatrixXd R, Eigen::MatrixXd P);
RcppExport SEXP KalmanRcppDemo_kalmanUpdate(SEXP YSEXP, SEXP XSEXP, SEXP FSEXP, SEXP HSEXP, SEXP QSEXP, SEXP RSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type F(FSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type H(HSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Q(QSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type R(RSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type P(PSEXP);
    __result = Rcpp::wrap(kalmanUpdate(Y, X, F, H, Q, R, P));
    return __result;
END_RCPP
}
